---
title: "The Emotional Body and Time Perception Replication Analysis"
output: html_notebook
---

### Libraries

```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(ez)
```

### Load the data
```{r}
prolific.data <- read_csv('data/prolific_data_timeperception.csv')
```

### Clean Up Data For Analysis
```{r}
data.testing <- prolific.data %>%
  filter(test_phase == "testing") %>%
  select(-row, -stimulus, -key_press, -trial_type, -trial_index, -time_elapsed, -stimulus_choice, -test_phase, -responses) %>%
  mutate(rt = as.numeric(rt), img_duration = as.numeric(img_duration))

data.testing
```

### Histogram of Response Times

```{r}
data.histogram <-
  ggplot(data = data.testing, aes(x=rt)) +
  geom_histogram(bins=100) +
  geom_vline(xintercept=25000, linetype="dashed")
         
data.histogram + labs(x="Response Time (ms)", y="Trial Count")
```

### Remove Responses With RT Outliers

```{r}
data.cleaned <- data.testing %>%
  filter(rt < 25000)

data.cleaned
```

### Add Column For Condition Type
```{r}
data.category <- data.cleaned %>%
  mutate(condition = if_else(grepl("blob", stim_name, fixed=TRUE), "blob", "orig")) %>%
  mutate(emotion = if_else(grepl("FE", stim_name, fixed=TRUE), "fear", "sad")) %>%
  mutate(correct = if_else(((img_duration >= 1000) & (responded == "short")) | ((img_duration < 1000) & (responded == "long")), FALSE, TRUE)) %>%
  select(-stim_name)

write.csv(data.category,'data/data_category.csv')
data.category
```

### Probability of Long Response For Each Img Duration
```{r}
data.prob.indiv <- data.category %>%
  group_by(subject_id, condition, emotion, img_duration) %>%
  summarize(p.long = sum(responded == "long") / n())

data.prob
```

```{r}
data.prob <- data.prob.indiv %>%
  group_by(condition, emotion, img_duration) %>%
  summarize(p.long.mean = mean(p.long), sd=sd(p.long), se=sd/sqrt(n()))

data.prob
```

### Figure 1
```{r}
ggplot(data=data.prob, aes(x=img_duration, y=p.long.mean, color=emotion, group=emotion)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept=.5, linetype="dashed") +
  labs(x="Image Duration (ms)", y="Probability of Long Response", color="Emotional Condition") +
  facet_wrap(~condition, labeller = labeller(condition=c(blob = "Asalient Images", orig = "Original Stimuli")))
```

### Probability of Long Response When Incorrect
```{r}
data.prob.wrong.indiv.prep <- data.category %>%
  group_by(subject_id, condition, emotion, responded) %>%
  summarize(p.wrong = sum(correct == FALSE) / n())

bad.subjects <- data.prob.wrong.indiv.prep %>%
  group_by(subject_id) %>%
  summarize(n=n()) %>%
  filter (n != 4) %>%
  pull(subject_id)

data.prob.wrong.indiv <- data.prob.wrong.indiv.prep %>%
  filter(!subject_id %in% bad.subjects)
```

### Probability of Long Response When Incorrect
```{r}
data.prob.wrong <- data.prob.wrong.indiv %>%
  group_by(condition, emotion, responded) %>%
  summarize(p.wrong.mean = mean(p.wrong), sd =sd(p.wrong), se =sd/sqrt(n()))

data.prob.wrong
```

### Figure 2 
```{r}
ggplot(data=data.prob.wrong, aes(x=condition, y=p.wrong.mean, fill=emotion)) +
  geom_col(position="dodge") +
  scale_x_discrete(labels = c("Asalient", "Original"))gith +
  labs(x="Stimulus Condition", y="Mean Probability of Long Response", fill="Emotional Condition") +
  facet_wrap(~responded) +
  geom_errorbar(aes(ymin=p.wrong.mean-se, ymax=p.wrong.mean+se), width=.2, position=position_dodge(.9))
```

### Analysis of Figure 2
```{r}
ezANOVA(data.prob.wrong.indiv, wid=subject_id, between = condition, within=c(emotion, responded), dv= p.wrong)
```


























